### PR TITLE
Generalize docset generation to aribtrary rustdocs

### LINKED ISSUE #3: Generalize for building any rustdoc-generated documentation
Occurred to me today it wouldn't be that hard, and would be very useful, to be able to generate docsets from rustdoc documentation for an arbitrary Rust crate with this tool. I think they could all go in the `rust` `DocSetPlatformFamily` and it would just work very smoothly.

### PR DESCRIPTION
**Pull request by tomjakubowski**
This is a huge pile of hacks, but it works.  The Rakefile now requires
some environment variables that set, in addition to the path to the
rustdoc output directory, the various names and identifiers used to name
and configure the docset.

Included is a script for generating the nightly docset and an example
script for would-be docset generators.  Eventually this capability
should be better-documented.

Close #3

### CODE REVIEW

**Comment by tomjakubowski** [comment]
cc @bvssvni would you like to give this a go before it's merged? You can include documentation for multiple crates into a single docset. For example, if you wanted to ship a docset for Piston and all of its subprojects:
1. Pick a directory to hold the rustdocs for all of your projects.
2. For each crate, run `rustdoc` with `--output` set to that directory. `rustdoc` will merge all of these crates into the same `search-index.js`, which is what we use to index the docset.
3. Copy `example.sh` and edit as you like. `DOCS_PATH` should be set to the directory in step 1. If your docset includes several crates, you could set `DOCSET_GROUP` so that the default `rustlibs` isn't used.
4. Run your script. You should have a `$DOCSET_NAME.docset` ready to open in Dash and ship!

If you hit an issue feel free to ping me on moz IRC (I am `dsrx`).

**Comment by tomjakubowski** [comment]
One thing to note: `Info.plist` isn't really documented and there's only [a single official example](http://kapeli.com/dash_resources/Info.plist) to go by, so I have no idea if we're doing the correct thing with those fields. I did find [some interesting use](https://github.com/Kapeli/cheatset/blob/master/lib/cheatset/creator.rb#L59-L68) of undocumented fields, but I've been scolded enough about using undocumented things in `Info.plist` :)

**Comment by bvssvni** [comment]
Works!

**Comment by indirect** [comment]
Awesome! :)

**Comment by tomjakubowski** [comment]
AWWWWW YEAAAAAAAA :mega: :mega: :mega: :mega:

**Pull request merged**
