### PR TITLE
Fix Enum indexing

### PR DESCRIPTION
**Pull request by wycats**
A change in the JS indexing is now reflected in the Ruby list.

We should consider trying to get all of this data represented as JSON so we can just load it in and call it a day. Protip™ to rust-doc: JavaScript supports JSON :smile:

### CODE REVIEW

**Comment by indirect** [comment]
Can you rebase so I can merge?

**Comment by wycats** [comment]
Done.

**Comment by wycats** [comment]
:+1:

**Comment by wycats** [comment]
Happy to have `Option` working finally! It was driving me crazy.

**Pull request merged**
