### PR TITLE
Fixes for latest nightly docs

### PR DESCRIPTION
**Pull request by tomjakubowski**
Wanted to give you a heads up that I'm working on updating this generator for the nightlies (though it's not quite ready yet). I know Dash ships with Rust documentation now, but unfortunately they become out of date rather quickly since they are only updated when Rust puts out a new official release. A number of changes were made to `rustdoc` since this repository was updated, and these fixes should reflect those.

Things left to do include:
- [x] Need to bundle and replace references to the online assets (fonts, logo) referenced in the Rust documentation.
- [x] I'd like to update the mapping of rustdoc item types to Dash item types, since I think Dash has added some more appropriate ones (like the Variant type, as one example).
- [x] More (all?) item names should be scoped to their crate and module, as the official Dash docset does.
- [x] Maybe the name of the docset should be changed to differentiate from the one shipped with Dash.
- [ ] TOC for items
- [x] Clean up HTML/CSS (remove sidebar/search area, remove " - Rust" from `<title>`)

### CODE REVIEW

**Comment by tomjakubowski** [comment]
Indexing is also rather slow (98.562 seconds to run `rake docset:reindex` on my 1.8 GHz i5 Macbook Air with 8 GB RAM). I don't know if it was always this way or if this is because of my changes, and it's difficult to test that without tracking down an old version of the docs compatible with the current code. I guess I'll see what the profiling story is for ruby.

**Comment by indirect** [comment]
All of those changes sound fantastic. I was much more excited about getting it working than making it fast, but I’m super happy for it to get faster, too. :)

There is now an official place to submit contributed Dash docsets, so it might event be possible to get nightly rust doc builds accessible without building it yourself: https://github.com/Kapeli/Dash-User-Contributions

**Comment by tomjakubowski** [comment]
Okay, I think this is ready for a review and merge. I haven't quite gotten to supporting Dash's TOC feature, which is very nice to have in the official docset, but this definitely produces a usable docset now.

**Comment by tomjakubowski** [comment]
Oh shoot, need to remove a few of the "Guides" still.

**Comment by tomjakubowski** [comment]
Okay _now_ it's ready :)

**Comment by indirect** [comment]
Looking great, thanks! :D

**Pull request merged**
